### PR TITLE
Adding EDA to our main notebook

### PR DESCRIPTION
**Pull request by monicafar147**
- [x] Add raw data from S3 bucket
- [x] Create a subset of data to work with
- [x] Identify common trends

### CODE REVIEW

**Comment by monicafar147** [comment]
Going to attempt to add S3 bucket data to our notebook using s3fs

**Comment by monicafar147** [comment]
This is too hard. Clearly there must be an easier way to load the data into our notebook using S3?
image

**Comment by monicafar147** [comment]
So this is an interesting graphic, but what does it mean?
image

**Comment by monicafar147** [comment]
This is the distribution of the average ratings 
image

**Comment by monicafar147** [comment]
The correlations go from 0.6 to 0.3 quite rapidly.
Shawshank Redemption is an intense life drama about unfair imprisonment.
The next correlated movie is 1984 which resonates with the unfair part.
image

**Comment by monicafar147** [comment]
@andamchako 
maybe we can run this command in Postgre SQL
`tag_df = tags.merge((g_scores.merge(g_tags, on='tagId')), on='movieId')`
then import the merged .csv  into python?

**Comment by andamchako** [comment]
@monicafar147 I'll try that. I'm also trying to save the merged files into Kaggle but I'm struggling.

**Comment by monicafar147** [comment]
image
I think it means the max rating is:

**Comment by monicafar147** [comment]
image

**Comment by monicafar147** [comment]
image

**Pull request merged**
